spring.datasource.url : jdbc:mysql://localhost:3306/web?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
spring.datasource.username : root
spring.datasource.password : testtest
spring.jpa.hibernate.ddl-auto: none
spring.liquibase.change-log: classpath:db/changelog/liquibase-outputChangeLog.yml
#spring.liquibase.enabled: false